# Generated by Django 3.2.4 on 2021-06-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='uuid',
            new_name='slug',
        ),
    ]
