# Generated by Django 3.2.4 on 2021-06-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210604_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='LinkUrl',
        ),
    ]
